### ISSUE TITLE
serve运行时报错

### ISSUE THREAD

**Issue by ziyu-bello** [buqiyuan/vite-vue3-lowcode#18]
![image](https://user-images.githubusercontent.com/82800128/153158172-3c4eda35-046e-47b5-8155-e6795505e383.png)

正常操作流程
git clone --single-branch https://github.com/buqiyuan/vite-vue3-lowcode.git
yarn
![image](https://user-images.githubusercontent.com/82800128/153158338-926bb541-7a99-4619-8e24-70c930ddcba4.png)
这个包要求node>16.9
nvm更换完之后运行就会出现上面的问题

yarn版本 1.22.10
node版本 16.9.0
npm版本 7.21.1

**Comment by ziyu-bello** [comment]
![image](https://user-images.githubusercontent.com/82800128/153159289-5f2233c8-eb9e-480c-b461-2c64c07338f7.png)
采用pnpm的时候能够正常到起到10086，但是访问的时候一直失败

**Comment by ziyu-bello** [comment]
pnpm在一直重试加载的过程中，突然就好了。。刚开始跑了几十分钟都一直failed。神奇

**Comment by buqiyuan** [comment]
重复刷新页面应该是antfu大佬的[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)的问题，下半年有空重构的时候再优化了

**Comment by buqiyuan** [comment]
不想有这个重复刷新页面的问题的话，可以用vben大佬的[vite-plugin-style-import](https://github.com/vbenjs/vite-plugin-style-import)替换unplugin-vue-components

**Comment by ziyu-bello** [comment]
soga，了解了解。谢谢大佬
