### ISSUE TITLE
大佬, PC 端 使用 UI 框架：Element Plus, 是否意味着还支持pc, 请问 在哪里预览 PC 版

### ISSUE THREAD

**Issue by Valar103769** [buqiyuan/vite-vue3-lowcode#6]

**Comment by buqiyuan** [comment]
PC端是有的，不过目前用于搭建内部管理系统去了，暂不开源

**Comment by Valar103769** [comment]
> PC端是有的，不过目前用于搭建内部管理系统去了，暂不开源

可以打听一下你们的实现吗 ,  pc端 也是用的h5的拖拽界面吗, 拖好了,再转成 pc 使用的 schema ? 还是 h5 和 pc , 要分开拖拽?

**Comment by buqiyuan** [comment]
PC端的与现在这个H5的拖拽有些不一样，PC端主要是基于layout和栅栏系统进行拖拽的，由于需求是针对PC端管理系统的，所以对H5适配很弱，PC端的后面可能只会增强对H5的适配，而H5端打算是做一些落地页之类的，所以打算分开做的
